{:profiles/dev {:env {:environment "development"
                      :host "127.0.0.1"
                      :port "8080"
                      :session-timeout-minutes "10000"
                      :idle-session-timeout-minutes "15"
                      :sql-dbtype "postgresql"
                      :sql-dbname "postgres"
                      :sql-host "localhost"
                      :sql-port "55432"
                      :sql-user "postgres"
                      :sql-password "postgres"
                      :dev-database "true"}}}
