{:profiles/dev {:env {:environment "development"
                      :host "127.0.0.1"
                      :port "8080"
                      :auth-secret "put a random base64 string here"
                      :auth-issuer "example.org"
                      :auth-audience "example.org"
                      :auth-token-name "Bearer"
                      :sql-dbtype "postgresql"
                      :sql-dbname "postgres"
                      :sql-host "localhost"
                      :sql-port "55432"
                      :sql-user "postgres"
                      :sql-password "postgres"
                      :dev-database "true"}}}
